# Generated by Django 2.2.6 on 2020-04-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='task',
            new_name='trip',
        ),
    ]
