# Generated by Django 2.2.6 on 2020-04-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0002_auto_20200409_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='trip',
            new_name='task',
        ),
    ]
