# Generated by Django 2.2.6 on 2020-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0005_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='altitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='locations',
            name='speed',
            field=models.CharField(max_length=100),
        ),
    ]
