# Generated by Django 2.2.6 on 2020-04-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0006_auto_20200420_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
