# Generated by Django 2.2.6 on 2020-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0007_locations_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='altitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='speed',
            field=models.FloatField(),
        ),
    ]
