# Generated by Django 2.2.6 on 2020-04-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0009_remove_locations_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='altitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locations',
            name='speed',
            field=models.CharField(max_length=100),
        ),
    ]
